/* Welcome to the SQL mini project. For this project, you will use
Springboard' online SQL platform, which you can log into through the
following link:

https://sql.springboard.com/
Username: student
Password: learn_sql@springboard

The data you need is in the "country_club" database. This database
contains 3 tables:
    i) the "Bookings" table,
    ii) the "Facilities" table, and
    iii) the "Members" table.

Note that, if you need to, you can also download these tables locally.

In the mini project, you'll be asked a series of questions. You can
solve them using the platform, but for the final deliverable,
paste the code for each solution into this script, and upload it
to your GitHub.

Before starting with the questions, feel free to take your time,
exploring the data, and getting acquainted with the 3 tables. */



/* Q1: Some of the facilities charge a fee to members, but some do not.
Please list the names of the facilities that do. */
Host: localhost

Database: country_club
Generation Time: Mar 03, 2019 at 10:26 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM Facilities WHERE membercost >0 LIMIT 0 , 30;
Rows: 5

facid	name		membercost	guestcost	initialoutlay	monthlymaintenance	
0	Tennis Court 1	5.0		25.0		10000		200
1	Tennis Court 2	5.0		25.0		8000		200
4	Massage Room 1	9.9		80.0		4000		3000
5	Massage Room 2	9.9		80.0		4000		3000
6	Squash Court	3.5		17.5		5000		80


/* Q2: How many facilities do not charge a fee to members? */

SQL query: SELECT * FROM Facilities WHERE membercost = 0 LIMIT 0, 30 ;
Rows: 4

facid	name		membercost	guestcost	initialoutlay	monthlymaintenance	
2	Badminton Court	0.0		15.5		4000		50
3	Table Tennis	0.0		5.0		320		10
7	Snooker Table	0.0		5.0		450		15
8	Pool Table	0.0		5.0		400		15


/* Q3: How can you produce a list of facilities that charge a fee to members,
where the fee is less than 20% of the facility's monthly maintenance cost?
Return the facid, facility name, member cost, and monthly maintenance of the
facilities in question. */
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1

SQL query: SELECT facid, name, membercost, monthlymaintenance FROM Facilities WHERE membercost < (.2*monthlymaintenance) LIMIT 0, 30 ;
Rows: 9

facid	name		membercost	monthlymaintenance	
0	Tennis Court 1	5.0		200
1	Tennis Court 2	5.0		200
2	Badminton Court	0.0		50
3	Table Tennis	0.0		10
4	Massage Room 1	9.9		3000
5	Massage Room 2	9.9		3000
6	Squash Court	3.5		80
7	Snooker Table	0.0		15
8	Pool Table	0.0		15




/* Q4: How can you retrieve the details of facilities with ID 1 and 5?
Write the query without using the OR operator. */
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM Facilities WHERE facid IN (1,5) LIMIT 0, 30 ;
Rows: 2

facid	name		membercost	guestcost	initialoutlay	monthlymaintenance	
1	Tennis Court 2	5.0		25.0		8000		200
5	Massage Room 2	9.9		80.0		4000		3000



/* Q5: How can you produce a list of facilities, with each labelled as
'cheap' or 'expensive', depending on if their monthly maintenance cost is
more than $100? Return the name and monthly maintenance of the facilities
in question. */

Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1

SQL query:
SELECT name, monthlymaintenance,
CASE WHEN monthlymaintenance > 100 THEN 'expensive' ELSE 'cheap' END AS cost_type
FROM Facilities
LIMIT 0, 30 ;
Rows: 9

This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
name		monthlymaintenance	cost_type	
Tennis Court 1	200			expensive
Tennis Court 2	200			expensive
Badminton Court	50			cheap
Table Tennis	10			cheap
Massage Room 1	3000			expensive
Massage Room 2	3000			expensive
Squash Court	80			cheap
Snooker Table	15			cheap
Pool Table	15			cheap


/* Q6: You'd like to get the first and last name of the last member(s)
who signed up. Do not use the LIMIT clause for your solution. */

Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query:
SELECT firstname, surname, joindate
FROM Members
WHERE joindate = (SELECT MAX(joindate) FROM Members) ;
Rows: 1

This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
firstname	surname	joindate	
Darren		Smith	2012-09-26 18:08:45


/* Q7: How can you produce a list of all members who have used a tennis court?
Include in your output the name of the court, and the name of the member
formatted as a single column. Ensure no duplicate data, and order by
the member name. */

Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query:
SELECT DISTINCT CONCAT(Members.firstname,' ',Members.surname) AS member_name,
Facilities.name AS court_name
FROM Members
JOIN Bookings ON Members.memid = Bookings.memid
JOIN Facilities ON Bookings.facid = Facilities.facid
WHERE Facilities.facid IN (0,1)
ORDER BY 1
LIMIT 0, 30 ;
Rows: 30

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
member_name	court_name	
Anne Baker	Tennis Court 1
Anne Baker	Tennis Court 2
Burton Tracy	Tennis Court 1
Burton Tracy	Tennis Court 2
Charles Owen	Tennis Court 2
Charles Owen	Tennis Court 1
Darren Smith	Tennis Court 2
David Farrell	Tennis Court 1
David Farrell	Tennis Court 2
David Jones	Tennis Court 1
David Jones	Tennis Court 2
David Pinker	Tennis Court 1
Douglas Jones	Tennis Court 1
Erica Crumpet	Tennis Court 1
Florence Bader	Tennis Court 2
Florence Bader	Tennis Court 1
Gerald Butters	Tennis Court 1
Gerald Butters	Tennis Court 2
GUEST GUEST	Tennis Court 1
GUEST GUEST	Tennis Court 2
Henrietta Rumney	Tennis Court 2
Jack Smith	Tennis Court 1
Jack Smith	Tennis Court 2
Janice Joplette	Tennis Court 1
Janice Joplette	Tennis Court 2
Jemima Farrell	Tennis Court 1
Jemima Farrell	Tennis Court 2
Joan Coplin	Tennis Court 1
John Hunt	Tennis Court 1
John Hunt	Tennis Court 2


/* Q8: How can you produce a list of bookings on the day of 2012-09-14 which
will cost the member (or guest) more than $30? Remember that guests have
different costs to members (the listed costs are per half-hour 'slot'), and
the guest user's ID is always 0. Include in your output the name of the
facility, the name of the member formatted as a single column, and the cost.
Order by descending cost, and do not use any subqueries. */

Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query:
SELECT Facilities.name,
CONCAT(Members.surname,' ',Members.firstname) AS member_name,
CASE WHEN Members.memid = 0 THEN Facilities.guestcost * Bookings.slots
ELSE Facilities.membercost * Bookings.slots END AS booking_cost
FROM Members
JOIN Bookings ON Members.memid = Bookings.memid
JOIN Facilities ON Bookings.facid = Facilities.facid
WHERE CASE WHEN Members.memid = 0 THEN Facilities.guestcost * Bookings.slots
ELSE Facilities.membercost * Bookings.slots END > 30
AND DATE(Bookings.starttime) = '2012-09-14'
ORDER BY 3 DESC
LIMIT 0, 30 ;
Rows: 12

This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
name		member_name	booking_cost	
Massage Room 2	GUEST GUEST	320.0
Massage Room 1	GUEST GUEST	160.0
Massage Room 1	GUEST GUEST	160.0
Massage Room 1	GUEST GUEST	160.0
Tennis Court 2	GUEST GUEST	150.0
Tennis Court 1	GUEST GUEST	75.0
Tennis Court 1	GUEST GUEST	75.0
Tennis Court 2	GUEST GUEST	75.0
Squash Court	GUEST GUEST	70.0
Massage Room 1	Farrell Jemima	39.6
Squash Court	GUEST GUEST	35.0
Squash Court	GUEST GUEST	35.0

SELECT Facilities.name,
       CONCAT(Members.surname,' ',Members.firstname) AS member_name,
       CASE WHEN Members.memid = 0
            THEN Facilities.guestcost * Bookings.slots
            ELSE Facilities.membercost * Bookings.slots
            END AS booking_cost
FROM Members
JOIN Bookings
     ON Members.memid = Bookings.memid
JOIN Facilities
     ON Bookings.facid = Facilities.facid
WHERE CASE WHEN Members.memid = 0
            THEN Facilities.guestcost * Bookings.slots
            ELSE Facilities.membercost * Bookings.slots
            END > 30
      AND DATE(Bookings.starttime) = '2012-09-14'
ORDER BY 3 DESC


/* Q9: This time, produce the same result as in Q8, but using a subquery. */

Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query:
SELECT facility, member_name, booking_cost
FROM ( SELECT Facilities.name AS facility,
CONCAT(Members.surname,' ',Members.firstname) AS member_name,
CASE WHEN Members.memid = 0 THEN Facilities.guestcost * Bookings.slots
ELSE Facilities.membercost * Bookings.slots END AS booking_cost
FROM Members
JOIN Bookings ON Members.memid = Bookings.memid
JOIN Facilities ON Bookings.facid = Facilities.facid
WHERE DATE(Bookings.starttime) = '2012-09-14' ) AS bookings
WHERE booking_cost > 30
ORDER BY booking_cost DESC
Rows: 12

facility	member_name	booking_cost	
Massage Room 2	GUEST GUEST	320.0
Massage Room 1	GUEST GUEST	160.0
Massage Room 1	GUEST GUEST	160.0
Massage Room 1	GUEST GUEST	160.0
Tennis Court 2	GUEST GUEST	150.0
Tennis Court 2	GUEST GUEST	75.0
Tennis Court 1	GUEST GUEST	75.0
Tennis Court 1	GUEST GUEST	75.0
Squash Court	GUEST GUEST	70.0
Massage Room 1	Farrell Jemima	39.6
Squash Court	GUEST GUEST	35.0
Squash Court	GUEST GUEST	35.0


/* Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members! */

Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query:
SELECT Facilities.name AS facility,
SUM(CASE WHEN Members.memid = 0 THEN Facilities.guestcost * Bookings.slots
         ELSE Facilities.membercost * Bookings.slots END) AS total_revenue
FROM Members
JOIN Bookings ON Members.memid = Bookings.memid
JOIN Facilities ON Bookings.facid = Facilities.facid
GROUP BY facility
HAVING total_revenue <1000
ORDER BY total_revenue
LIMIT 0, 30 ;
Rows: 3

This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
facility	total_revenue	
Table Tennis	180.0
Snooker Table	240.0
Pool Table	270.0




